language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/codeception/codeception/codecept run unit
  - ./vendor/codeception/codeception/codecept run functional
